# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6983bf33fc2f4e1e6d3acdb656df3a7003d62258a1c9e12930e207deb00f86f29ee134bd89a41faba5bfffe2d7e1b5d57691ef3c2df06d791ba560a477d65d5c

test:
  secret_key_base: da37c1953510867eb9392d7a49031a096cb10ff7c121f87054ec69b6c7da4cb0f02149f1ea31fa754655e4c7c55373d0b3f24c762781ddf019ac810f07d45165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
