# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9807dd26101f9ee70ad40321d5e503e839fe1f4d346510214636a5bb69382b40917a5516da3326a678062b45b1da38b650419d352866c3690f1331f4e9c3d39

test:
  secret_key_base: fa55bc6b0dd5e3c6650c1f5334c80d921cc02e5369982787780c7a33d32aa0356692a30d34576070f9497f4c6bb7a946b9afe0379cb669a9d5d5640a42668bf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
