# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15ef59ebe8c393b6c30a6c0d73949202599154df6999f0dc512029c076e5866ffe814acd853e833d66115aa3596d24725e879b9097a6400a70327c4c3fbcf488

test:
  secret_key_base: e92d429ed112e60c64983f266a1093819e1ac598bc881afb83a65e8fda981559c930d68cbfa69f3ac148d68a1a0302d58ecc916430aea3ac1df584f106c84150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
